### ISSUE TITLE
PM Review: User Auth

### ISSUE THREAD

**Issue by jbieze** [jbieze/twsclone#7]

**Comment by s-pangburn** [comment]
Make sure to add your Heroku link to the wiki!

**Comment by jbieze** [comment]
Okay, I just got it set up. https://github.com/jbieze/twsclone/wiki <https://github.com/jbieze/twsclone/wiki> or https://tws-clone.herokuapp.com/#/ <https://tws-clone.herokuapp.com/#/>, whichever you prefer.

**Comment by s-pangburn** [comment]
Haha, I love the snarky headlines on the auth form. Well played.

### Things to fix

1. The sign in/sign up button should change your cursor to that glove-hand on hover. This makes it more obviously "clickable". It's pretty simple, just set the css like so: 
```
.button-class:hover { 
   cursor: pointer; 
}
```

2. It's kind of awkward that the "Did you get lost?" and the errors are the same color. Try to keep them visually separate. (I have to admit though, it is kind of funny that it looks like it keeps asking you whether you're lost every time you fail to login)

3. The greeting and logout button should be horizontal. I know this is a pain to deal with, if you're using flexboxes, try setting the `flex-direction` for the div to `row`.

4. Do `cursor: pointer` for your logout text, too.

5. Usernames should probably be unique. I signed up twice under the same username using a different email. If two people had the same username and password, this might become a problem.

6. There should be a demo login!

Overall, it's looking good! Just make these tweaks and it should be solid.

**Comment by s-pangburn** [comment]
Signup form doesn't display any errors right now. That's really it, though! Fix that and I'll mark the feature as done!

**Comment by s-pangburn** [comment]
Oh, uh, also if you're logged in, you can still click "Let's Get Tea!" and it takes you to the signup page. You should probably change that link to send you to the cities page or something if you're already logged in.
